### ISSUE TITLE
Working with dynamic component

### ISSUE THREAD

**Issue by nvthuong1996** [nuxt/components#107]
Is it possible to pass an option to allow register global components with a predefined prefix to use dynamic components ?

**Comment by LeCoupa** [comment]
Hey @nvthuong1996 you should take a look at this thread https://github.com/nuxt/components/issues/13

**Comment by nvthuong1996** [comment]
@LeCoupa  thank you

**Comment by LeCoupa** [comment]
You are welcome! If you can close your issue :)
