### ISSUE TITLE
IE10 syntax error, const not transpiled in ES5

### ISSUE THREAD

**Issue by maksimyurkov** [nuxt/components#109]
### Versions

- nuxt v2.14.7
- node v14.15.0
- npm 6.14.8
- IE10 (emulator in IE11)
- Windows 10 (x64)

### Reproduction

Default Nuxt application

`npx create-nuxt-app my-app`

Options
- NPM
- Single Page App
- Static
- Other options = Default

### Steps to reproduce

`npm run dev`

### What is Expected?

Correct work in Internet Explorer 10

### What is actually happening?

Page not working. Syntax Error, 'const' not transpiled.
Мy colleagues (with other system configurations) have the same problem.

![image](https://user-images.githubusercontent.com/17424327/98014586-e2e48500-1e0c-11eb-942e-8610ae136343.png)

P.S. In nuxt.config.js when i set "components": false, all working.

**Comment by pi0** [comment]
Thanks for report. Issue should be fixed in [v1.2.1](https://github.com/nuxt/components/releases/tag/v1.2.1) by 04bea9bc3e44533fc6c6128234a7c13eb3f704ce. You can get update using `yarn upgeade @nuxt/components` or `npm up @nuxt/components`. Please reopen if still not working.

**Comment by maksimyurkov** [comment]
> Thanks for report. Issue should be fixed in [v1.2.1](https://github.com/nuxt/components/releases/tag/v1.2.1) by [04bea9b](https://github.com/nuxt/components/commit/04bea9bc3e44533fc6c6128234a7c13eb3f704ce). You can get update using `yarn upgrade @nuxt/components` or `npm upgrade @nuxt/components`

Thanks for help! After 1.2.1 upgrade error persisted, since in installComponents.js there was one more 'const':

`const functionalPatchKey = '_functionalComponents'`

If change this 'const' to 'var' all OK, working in IE9 IE10, I checked.

**Comment by pi0** [comment]
https://github.com/nuxt/components/releases/tag/v1.2.2
