### ISSUE TITLE
What is the complexity of adding a suffix modifier in addition to a prefix modifier?

### ISSUE THREAD

**Issue by dsmurrell** [nuxt/components#112]
I can see many examples where it reads better to use a suffix instead of a prefix.

For example:

I have some chart components in `components/chart/` called `Bubble.vue`, `Bar.vue`
I have some field components (used to edit a field in the DB) in `components/field/` called `Date.vue`, `Image.vue` and `Json.vue`

Calling these would be more natural with a suffix as `BubbleChart`, `BarChart`, `DateField`, `ImageField`, `JsonField`.

Is the addition of a suffix technically possible? If so, I can begin work on adding one as long as there is a good chance it's accepted.

**Comment by pi0** [comment]
Hi @dsmurrell. Technically suffix is also possible but would be much better if you use consistent component name as file also according to vue style guide. Like `components/chart/ChartBar.vue` and also it adds complexity to current name resolver.

Finally, It is possible using `'components:dirs'` hook to add suffix if you really want.
