### ISSUE TITLE
Global directory path attempts to resolve TS component twice

### ISSUE THREAD

**Issue by oinkbark** [nuxt/components#117]
**Describe the bug**
If you use TS and split your component into multiple files, you cannot use a directory named "global", otherwise it tries to add duplicate components.

I had my app set to auto build with the latest NPM packages, and this new update made my Nuxt project build fail with this warning:
```
Two component files resolving to the same name TheNavbar:
 - /app/src/components/global/TheNavbar/TheNavbar.vue
 - /app/src/components/global/TheNavbar/TheNavbar.ts
```

**To Reproduce**
> **nuxt.config.js**
```js
export default {
  components: [
      { path: '@/components/', extensions: ['vue'] }
  ],
  buildModules: [
      '@nuxt/typescript-build',
      '@nuxt/components'
  ]
}
```
> **/components/global/TheNavbar.vue**
```vue
<template src="./TheNavbar.pug" lang="pug"></template>
<script src="./TheNavbar.ts" lang="ts"></script>
<style src="./TheNavbar.styl" scoped lang="stylus"></style>
```

**Expected behavior**
It does not try to load the component twice.

**Additional context**
- Version: 1.2.0
- Setting "global: false" does not fix the issue.
- I do not use dynamic components. This was just the way I had my directory structure laid out.
- If I rename the directory to anything else, such as "omni", it works just fine.
- It also generates this render error as a side effect. I can provide the full "frames" array if needed:
```json
  "error": {
    "message": "render function or template not defined in component: TheNavbar",
    "name": "Error",
    "frames": [ ],
    "hasInternal": true
  }
```

**Comment by pi0** [comment]
Hi. Thanks for detailed report. Issue should be fixed in v1.2.1 by #120. You can get update using yarn upgrade @nuxt/components or npm upgrade @nuxt/components. Please reopen if it is not.
