### ISSUE TITLE
Components are not found when using is-Directive

### ISSUE THREAD

**Issue by hv-pul** [nuxt/components#13]
**Describe the bug**
I expected components to be available for use via `is`, like this:
`<component is="ComponentName">`

But from the error log it seems that the components are not registered.

**To Reproduce**
Check the console output at https://codesandbox.io/s/nuxt-components-fdcw5?file=/components/LazyComponentA.vue

**Expected behavior**
Components should render the same as if using them directly.

**Additional context**

**Comment by kevinmarrec** [comment]
Hi @hv-pul ,

`<component>` is intended to only be used with `is` value being a dynamic variable.
And the variable being dynamic, Nuxt.js can't determine which components to import.

We've been thinking of a possible implementation with automatic performance boost by lazy loading the components required this way :

```
<template>
  <!-- @components: A, B --> 
  <component :is="componentName" >
  <button @click="componentName = 'B'">Change Component</button>
</template>

<script>
export default {
  data () {
    return {
      x: 'A',
    }
  }
}
</script>
```
> Will automatically lazy import `A` and `B`, which means `B` will only be used (downloaded) if the button is clicked.

What do you think ?

**Comment by f3ltron** [comment]
It make sens to add comments like this. As in production it's almost impossible to know before wich componnents will be there. In this case you will add all components in the bundler that is not possible. 

Definitely cool. As i need it too ^^. I hope it i will come soon :)

**Comment by hv-pul** [comment]
Hi @kevinmarrec,

thanks a lot for your explanation. I mistakenly thought that all components would be imported gloablly, but I see you parse the markup instead.

I have to say I'm not a big fan of the magic comment annotation. It does not seem very Vue-idiomatic to me. It would In that case I guess you could just as well use explicit imports or a dynamic pattern like [this](https://itnext.io/vue-a-pattern-for-idiomatic-performant-component-registration-you-might-not-know-about-9f3c091846f5). And it would be very hard to keep track of which components you install where.

Three thing come to my mind:

- An optional `NuxtComponent`-component, in which all components are installed globally (as lazy imports). Usage would be just like the usual case: `<NuxtComponent :is="MyComponent">`, which would lazyload the `MyComponent`-chunk. That would mean that some unnecessary chunks are generated when `NuxtComponent` is used, but at least they would not be loaded, and it's up users whether they decide to use it. 

- a global nuxt.config option where you can set the components that will be globally installed to the `NuxtComponent` (or even any component), ideally with the option to glob directories. As the chunks for any use of the ´<component>´-Tag need to be generated anyway, even with the comment syntax you suggested, that would at least keep things in one place, so it seems less brittle to me. So something like this:
```js
  components: {
    globalInstall: ['components/builder/**/*.vue', 'components/global/myComponent.vue']
  }
```

- If you go with the comment-route, could you allow glob-patterns? That way at least it would be easier to handle something like page builder patterns, with a lot of dynamic components (could easily be dozens or more) that would need to go in the comment. So something like `<!-- @components /components/builder/**/*.vue -->`

**Comment by f3ltron** [comment]
in terms of having a small chunk as a possible i am not a fan of having by default like global components register for dynamics. I have like 130 components in my project so... that have a lot of dynamics dependencies.

I like the idea of comments clear and simple

**Comment by papertokyo** [comment]
If components that could potentially be lazy loaded need to be specified (which is reasonable), then I think a `nuxtComponents` option with an array of component names is preferable to the magic comment. 

The exported object is where all the other options regarding component logic live, so that's where I'd expect to specify this kind of thing.

**Comment by aerophobic** [comment]
I would vote for option 4 of the proposal from @hv-pul with the `nuxtLazyComponents `(or whatever that prop is called) being a function returning the array of component names. afaik all components in a project are indexed. mapping that array of indexed components with the defined array in specific component with the `nuxtLazyComponents `defined will make it possible to lazy load the components as dynamic components easily (at least with dynamic imports)

**Comment by loomchild** [comment]
I like the 2nd option, available for any <component>, with an option to glob directories.

My personal use case is that I have a site that is built in CMS and I don't know which sections / components will be used in advance.

**Comment by papertokyo** [comment]
@dan-hammond If I understand your intention correctly, that's possible with Vue's async components functionality. I'm loading dynamic sections on a page (with the data from a CMS) with code something like this:

```
<template>
  <component
    :is="component"
    v-if="component"
    v-bind="section"
  />
</template>

<script>
export default {
  props: ['section'],

  computed: {
    component() {
      try {
        if (this.section && this.section.typeName) {
          return () => import(`~/components/${this.section.typeName}`)
        }
      } catch (err) {
        // noop
      }
    }
  }
}
</script>
```

**Comment by dan-hammond** [comment]
@papertokyo Thanks for the input. 

You're right that the `<component :is>` route works, it's what I'm currently using. My main reason for wanting to use this is to avoid having to fiddle with Webpack config myself, as I think by default Webpack will pack all of my dynamically imported components in one large chunk.

As I'm planning to use this as a router alternative, I'd like to maintain route level code splitting.

Thanks again.

**Comment by papertokyo** [comment]
@dan-hammond Makes sense. I didn't realise Webpack chunked them all together...that kind of defeats the purpose of importing components dynamically, at least from a bundle size perspective. 🤔

**Comment by jbnv** [comment]
I need some variation of this functionality to enable role-based content on my site. The component rendering the content doesn't know what the possible values of the roles are. The content is basically an component, and I'd like to keep it that way for consistency.

**Comment by gilles6** [comment]
This works:
```
<QuestionCheckbox question="How are you ?" />
```
This also works:
```
<QuestionCheckbox question="How are you ?" />
<component :is="'QuestionCheckbox'" question="Where are you ?" />
```
But this alone doesn't work:
```
<component :is="'QuestionCheckbox'" question="Where are you ?" />
```
With error message:
>  Unknown custom element: <QuestionCheckbox> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

How should I fix it ?

**Comment by aerophobic** [comment]
This is the expected behaviour. If you place the component inside your template as following:
```
<QuestionCheckbox question="How are you ?" />
```
`@nuxt/components` module finds it while parsing your single file components and loads the component file `QuestionCheckbox.vue`. If it is only placed as dynamic component `@nuxt/components` does not dynamically import `QuestionCheckbox.vue`.

**Comment by gilles6** [comment]
@aerophobic Thanks for this answer.

So, what should I do ?

My `nuxt.config.js` is set as below:
```
components: {
  dirs: [
    '~/components',
    {
      path: '~/components/foo/',
      prefix: 'Foo'
    },
    {
      path: '~/components/question/',
      prefix: 'Question'
    }
  ]
},
```

**Comment by aerophobic** [comment]
@gilles6 you cannot dynamically load dynamic components as you try to - by now at least. That's what the whole issue is about ;) However, I managed to build a workaround with the help of `vue-lazy-hydration` package. I can describe my approach to do this if you are interested.

**Comment by gilles6** [comment]
My current workaround is this:
```
<div v-for="(item, index) in list" :key="index">
  <QuestionCheckbox
            v-if="item.type === 'checkbox'"
            :question="item.question"
          />
  <QuestionRadio v-else-if="item.type === 'radio'">
  ...
</div>
```
Much more verbose, but it works.

**Comment by cavi21** [comment]
hey @gilles6 it would be great if you share your approach  using `vue-lazy-hydration`! thanks

**Comment by cavi21** [comment]
hey @aerophobic it would be great if you share your approach  using `vue-lazy-hydration`! thanks

**Comment by israelroldan** [comment]
@kevinmarrec I wonder if there's perhaps room to explore a similar approach to what content is doing (having a special directory that is treated as global components to always be loaded).  

### From https://content.nuxtjs.org/writing#table-of-contents :
![image](https://user-images.githubusercontent.com/159962/94543467-675e4980-024a-11eb-9373-e2b4ca85d1d8.png)

**Comment by samuells** [comment]
I would be definitely interested in some kind of way/pattern to define these dynamic components. Especially in my case using Storyblok CMS I don't know often which components should I render. What I often know is a list of possibilities. So Option 4 looks like a way to me. 😇

**Comment by aerophobic** [comment]
@gilles6 @cavi21 @samuells It's been some time, but I was able to write down the idea and how to solve this problem. You can checkout my explanation [on medium](https://julianderungs.medium.com/crank-up-auto-import-for-dynamic-nuxt-js-components-54e7f198fc16).
I prepared a nuxt module to provide a `NuxtDynamic` component which works as stated before: [@blokwise/dynamic](https://www.npmjs.com/package/@blokwise/dynamic)

@samuells there is also a wrapper for `NuxtDynamic` which renders components based on storyblok schemas, checkout the [@blokwise/blok](https://www.npmjs.com/package/@blokwise/blok) module.

**Comment by pi0** [comment]
Hi. Sorry this issue left unanswered. Actually by `global` option it is possible to use dynamic components.

```js
// nuxt.config.js
export default {
  components: [{ path: "~/components", global: true }]
}
```

```html
<template>
  <div>
    <h2>Nuxt Dynamic Components</h2>
    <div v-for="name in ['test1', 'test2']" :key="name">
      <component :is="name"></component>
    </div>
  </div>
</template>
```

([sandbox](https://codesandbox.io/s/khhh7))

Please note that `global` option does not means components are added to main chunk but they are dynamically imported with webpack  (see [here](https://github.com/nuxt/components/blob/master/templates/components/plugin.js) and [here](https://codesandbox.io/s/khhh7?file=/.nuxt/components/plugin.js)) 

This option is disabled by default purposefully because forcing webpack to make one async chunk per-component makes chunking less efficient (this is same technique used by @aerophobic module) so you have to only use for dirs/when when dynamic components are necessary

**Comment by Decipher** [comment]
@pi0 Thanks for the clarification. I have been using the `global` approach myself, and it was working fine, but I assumed it was being added to the main chunk.

**Comment by sugoidesune** [comment]
Any tips on how to use this `import(`~/node_modules/UILibrary/${this.component_name}`)` ?
The import route gets scrambled  by I assume webpack and doesn't work. In particular I am trying to do this with vuetify.

**Comment by scscgit** [comment]
I'm having an issue with `<component>` not loading a component that's imported automatically (unless it's imported directly), including a (treeshaked?) Vuetify component, or one from my project - **but only when the page is generated using `nuxt generate`**. The `nuxt dev` page works correctly. Has anyone observed the same issue?

By the way, this issue is really a pain to debug due to a lack of warnings about the reason why the component wasn't included; is there no chance of implementing some warnings to be displayed to developers who use a `<component>` with a component that wasn't automatically imported by `nuxt/components`?

Also I've been unable to use the aforementioned `globals` to import a Vuetify component, so I assume the only option is to import a component directly within our Vue component where we're (dynamically) using it. As Vuetify supports treeshaking, I had hoped that we could globally reference its components by name (rather than a full import path), for example in the global components configuration block (as it's already imported and has a "name"), but this doesn't seem to be supported.

**Comment by joaojuicee** [comment]
The solution shown by @pi0 doesn't seem to be working as of nuxt ver. 2.15.3

**Comment by staszewski** [comment]
I have still similar problem with nuxt-content component. I followed https://github.com/nuxt/components/issues/13#issuecomment-630283808 This make it so string "object Object" is passed as prop and no content is rendered. No error in tests regarding `[Vue warn]: Unknown custom element:`. I know it happens in component from different lib, but it looks like its related to nuxt more than to its modules. Any idea?

```
<template>
  <article>
    <h1>{{ article.title }}</h1>
    <p>{{ article.description }}</p>
    <NuxtContent :is="componentName" :document="article" />
  </article>
</template>

<script lang="ts">
import Vue, { PropType } from 'vue'
import { IContentDocument } from '@nuxt/content/types/content'

export default Vue.extend({
  name: 'Article',
  props: {
    article: {
      type: Object as PropType<
        IContentDocument & { title: string; description: string }
      >,
      default() {
        return {
          title: 'Something went wrong',
          description: 'Please go to main page',
        }
      },
    },
  },
  data() {
    return {
      componentName: 'A',
    }
  },
})
</script>
```

When there is no "is" prop content is rendered correctly, but I have warning while running unit tests. Any ideas how to fix it?

**Comment by samuells** [comment]
Ok. I just wanted to confirm, that the dynamic components import works already even without specifying `global: true`. I tested on my Storyblok project, where I am getting the name/type of the component from API and the `<component :is="variable"/>` approach worked.

**Comment by valentinoli** [comment]
I'm having an issue that only appears in the production build. I am using Nuxt **v2.15.8**

I have:
```html
<component :is="theComponent" />
```

where `theComponent` is a String.

It doesn't render the component and results in the following comment node:
```
<!--function(a,b,e,n){return Qe(t,a,b,e,n,!0)}-->
```

I am using component auto-importing with `components: true`, and I assume dynamic components are available globally

**Comment by shtse8** [comment]
> components

no, as tested, `components: true` won't have flag `global: true`.
```
{
    path: '/components'
},
```

**Comment by 300code** [comment]
not working with vite at all
