### ISSUE TITLE
how to use hook types in module nuxt.ts

### ISSUE THREAD

**Issue by reslear** [nuxt/components#134]
how to use types in `nuxt.ts`

its my current solution 

```ts

const nuxtModule: Module = function (moduleOptions) {
  const { nuxt } = this;

  const hookCb: NuxtOptionsHooks["components:dirs"] = (dirs) => {
    dirs.push({path: join(__dirname, "components"), prefix: 'aw'});
  };

  nuxt.hook("components:dirs", hookCb);
}
```
my problem in `nuxt.hook` return `any` type, and not auto set `dirs` types

how to write better ?

**Comment by reslear** [comment]
@kevinmarrec help please :)

**Comment by reslear** [comment]
No type errors in my solution
Yes, this is writing style only, for beauty)

**Comment by pi0** [comment]
Since we don't have types for `Nuxt`, writing style seems good. It could be nice if we exported types like `componentsDirHook` and `ComponentsDir` from `@nuxt/components` anyway...

**Comment by reslear** [comment]
@pi0 thank you, I'll leave it as you said) and good remark for need exported types for use in other places, and same problem for exporting types in https://github.com/nuxt/image/issues/161 )

**Comment by pi0** [comment]
@reslear PR welcome to export types :)

**Comment by NozomuIkuta** [comment]
I submitted a PR, and I hope it will help.
