### ISSUE TITLE
Set Global to True, with html file template and typescript

### ISSUE THREAD

**Issue by kakiman** [nuxt/components#144]
**i don't know if it's a bug or new feature.**

For my projects, i use multi-file component structure with 4 files: .ts, .html .scss and .vue.

The vue file is only use for import the 3 others: 
```
<template lang="html" src="./MyComponent.html"></template>
<script lang="ts" src="./MyComponent.ts" name="my-component" />
<style lang="scss" src="./MyComponent.scss" scoped/>
```

So, it's just to notice you if we use and external template file like .html we should add `global: true` in the module configuration to work 
```
components: [
    {
      path: '~/components',
      extensions: ['vue'],
      global: true
    }
  ]
```

With this configuration we are able to not import the component into our .ts file

**Comment by pi0** [comment]
Hi @kakiman. Would you please specify used nuxt version? In 2.15+ global option removed (it is enabled for all components)

**Comment by kakiman** [comment]
hi @pi0, i use the 2.14.12 of nuxt.
so if i uprgrade my nuxt to the latest it should be work fine ?

**Comment by pi0** [comment]
I guess so :) 

Release notes: https://github.com/nuxt/nuxt.js/releases/tag/v2.15.0

**Comment by pi0** [comment]
Closing since it was a known limitation for components v1 that loader cannot scan html templates.

**Comment by kakiman** [comment]
Ok, this works well thank you ;-)
Sorry for the inconvenience
