### ISSUE TITLE
v2 auto import via option key name rather than folder structure

### ISSUE THREAD

**Issue by alexcroox** [nuxt/components#151]
In Nuxt < v2.15 (components v1) I simply had:

`components: true`

And my component naming and folder structure was then free for me to organise how I pleased.

I could simply use whatever the component's { name: } was, ignoring any folder structure that lead to it. 

I can't seem to replicate this functionality in v2, I've tried listing all my folders in the components config but there's still plenty of edge cases where this doesn't work, e.g

```
components: [
    '~/components/elements/base',
    '~/components/elements/form',
    '~/components/elements/typography',
    '~/components/forms',
    '~/components/guards',
    '~/components/layouts',
    '~/components/layouts/admin',
    '~/components/modals',
    '~/components/nav',
    '~/components/utils',
    '~/components/widgets'
  ],
```

**How do I get v2 to ignore the folder structure and just use the component's `name:` option key to auto import like v1 did.**

**Comment by pi0** [comment]
Hi. Using latest version of components (2.1+), you can use `pathPrefix: false` like this:

```js
components: [
  { path: '~/components', pathPrefix: false }
]
```

**Comment by alexcroox** [comment]
Ah great thanks, what would be the best way of utilising 2.1, is it possible without waiting for `nuxt` to release a new version?

**Comment by pi0** [comment]
@alexcroox If you update to 2.15 and recreate lock-file, it will install latest version :)

**Comment by alexcroox** [comment]
@pi0 any chance of Nuxt updating to latest components in it’s next patch? This is a blocker for me updating and taking advantage of the other 2.15 goodies 🙂

**Comment by pi0** [comment]
Hi @alexcroox. Actually latest nuxt (2.15.2) requires latest version of components (^2.1.2) which includes `pathPrefix` option.

BTW like i said you don't need to wait for nuxt released to get feature and patchs of components. You can recreate lockfile or use `yarn upgrade nuxt` or `npm up nuxt` (since components is defined by caret range. [learn more](https://docs.npmjs.com/about-semantic-versioning))
