### ISSUE TITLE
Beware of nuxt/components 2.0 and Nuxt 2.15 module errors

### ISSUE THREAD

**Issue by regenrek** [nuxt/components#153]
Hi,

I recognized that `pathPrefix: true` is now a default option for `nuxt/components@2.0` or in other words, you have to disable `pathPrefix` to avoid breaking some third-party modules out there. 

Especially with the upgrade of [nuxt 2.15](https://github.com/nuxt/components#migration-guide) some migration to modules has to happen if you want to keep the old prefered directory structure.

Example directory structure

```
atoms/Image
atoms/Burger
molecules/Nav
```

### No Prefix style

`pathPrefix: false`
```
import { Image, Burger, Nav } from '@mylib/components'
```

#### Migration

If you still prefer the above style change the options in your
`nuxt.config.js` file.

From
```js
 components: '~/components'
  // or
 components: true
```

To
```js
  components: [{ path: '~/components', pathPrefix: false }],
```

### New default `nuxt/components@2.0.0`

`pathPrefix: true` <-- default
```
import { AtomsImage, AtomsBurger, MoleculesNav } from '@mylib/components'
```

I personally liked the previous design better but that's not my decision. Thanks for the awesome work. 

Regards

**Comment by pi0** [comment]
Hi dear @regenrek. Actually we **was** doing prefix in previous version as well but only for one upper level directory (`components/foo/bar/baz.vue` => `BarBaz` now it is `FooBarBaz`). This is to encourage using semantic directory structure but for bigger projects that need atomic design it makes sense to disable `pathPrefix` or explicitly define directories.
