### ISSUE TITLE
Cannnot auto import functional component

### ISSUE THREAD

**Issue by existe-deja** [nuxt/components#159]
**Describe the bug**
If I want to use functional components, I have to explicitly import them otherwise it throws `_vm._ssrNode is not a function`

**To Reproduce**
Comment/uncomment the import line 8 and line 12
https://codesandbox.io/s/quizzical-voice-80xzj?file=/pages/index.vue

**Expected behavior**
I should be able to use Functional Component with the `components: true` option in `nuxt.config.js`

**Additional context**
A quick fix is to explicitly import them so it's not a blocking problem.

**Comment by schneefux** [comment]
This is probably related to #126

**Comment by mathe42** [comment]
Same for me this is preventing me from updating nuxt. :(

**Comment by existe-deja** [comment]
@mathe42 a quick fix is to manually import your functional component when you use it. They do still work, only the auto import is broken.

**Comment by mathe42** [comment]
I know but as I use this for external libs it is not a practical solutions.

**Comment by apithy-isidro-martinez** [comment]
happened to me, just upgrade to version 2.15.3

**Comment by apithy-isidro-martinez** [comment]
> @mathe42 a quick fix is to manually import your functional component when you use it. They do still work, only the auto import is broken.

happened to me, just upgrade to version 2.15.3

**Comment by dpschen** [comment]
This might be solved by https://github.com/nuxt/components/releases/tag/v2.1.4

**Comment by pi0** [comment]
I can confirm issue fixing in sandbox by recreating `yarn.lock` to get latest components update.
