### ISSUE TITLE
Abnormal behaviour on Netlify

### ISSUE THREAD

**Issue by simeon9696** [nuxt/components#170]
**Describe the bug**
[I think] components on with the same name in the prefix as the page name does not load *on Netlify* 

I would be happy to provide more information if needed. But I'll start with the below details. 

I have a page `orderdetails.vue` and inside has four components. Inside the `components` folder for my project I have the structure as shown below: 

```
components/
├── orderDetails/
│   ├── Actions.vue
│   ├── Firestore.vue
│   └── Timeline.vue
├── orderDialog/
│   ├── requestEdit.vue
```

With this structure in mind I loaded in the components in `orderdetails.vue` like below:
```
<template>
  <v-container>
     <h1>Order Summary</h1>

    <OrderDetailsFirestore />
    <OrderDetailsActions />
    <OrderDialogRequestEdit />

    <v-row>
      <v-col >
        <h3>Order Timeline</h3>
        <span>{{new Date()}}</span>
        <LazyOrderDetailsTimeline/>
      </v-col>
    </v-row>
  </v-container>

</template>
```
While developing, this worked fine.  All the components loaded in as expected. Ran `npm run generate` then `npm run start` and that worked too. I should note in each of the four components above in the `created` hook I logged `created 'name' of component`.

When I deployed to Netlify however, all the components under the `orderDetails` folder did not load or log to the console only the one name `requestEdit` did. I changed the name of the folder from `orderDetails` to `orderParams` updated the template to include the new folder name prefix and then it worked. 

This is especially confusing since I have loads of other component folders with the exact same folder name as the page name and the components don't give trouble to load at all.

If anyone can offer insight on this I'd appreciate it. Even though my project is working now, I still don't what caused it and how to avoid it in the future.

**Expected behavior**
Components auto load as normal

**Comment by pi0** [comment]
Hi dear @simeon9696. Without reprodution it might be tricky to track down issue but it might be helpful if you can locally run `nuxt build` and check `.nuxt/components/readme.md` (there is a console log entry).
