### ISSUE TITLE
Tree shaking doesn't appear to work

### ISSUE THREAD

**Issue by alexblunck** [nuxt/components#176]
**Describe the bug**
When using the auto import components feature, unused components are bundled with builds. 

**To Reproduce**
1. Clone this repository https://github.com/nuxt/components
2. In the example project remove `<ComponentC />` from `pages/index.vue`
3. Run `yarn build -a`
4. See analyze output (`ComponentC` is present in the app.*******.js chunk)

**Expected behavior**
That `ComponentC` is not included in the bundle. Furthermore shouldn't components be bundled with the page chunks they are used in to match the behaviour when manually importing components?

**Screenshots**
<img width="296" alt="Screenshot 2021-03-31 at 11 11 17" src="https://user-images.githubusercontent.com/614291/113120562-0112ad80-9212-11eb-80aa-49347aa0cd99.png">

**Additional context**
-

**Comment by pi0** [comment]
Hi dear @alexblunck. Actually, tree-shake is happening but all component chunks are generated (as well) to be lazily imported on demand (this is called the hybrid loader approach). To confirm, you can open index page in browser to see that `ComponentC` is not loaded.

**Comment by alexblunck** [comment]
Hi @pi0, thanks for the quick reply! When running `nuxt build` and inspecting the output "app" chunk js file, which is loaded by the browser, the unused ComponentC component is present in the bundle. Is that the expected behaviour?

**Comment by pi0** [comment]
I can't tell without having access to deployment or full result of bundle analyzer. But it is mostly an issue with wba. Only chunk names are preset in app manifest chunk. BTW best would be checking devtools on real deployment to see what resources get load (since async components have a chunk each)

**Comment by alexblunck** [comment]
I created the simplest nuxt project to reproduce the issue: https://github.com/alexblunck/nuxt-tree-shaking.

It includes two components, `ComponentA` & `ComponentB`. Only `ComponentA` is referenced in `pages/index.vue`.

When you build the project or run `nuxt build -a` you can see, that `ComponentB` is also included in the "app" chunk which is served with every page load. 

I've included the analyze output in the `stats` folder in the repo, or you can view it here: https://rawcdn.githack.com/alexblunck/nuxt-tree-shaking/2ab735df5d2de475b9740a9bc0ae4e2f6cf2c604/stats/client.html.

**Comment by pi0** [comment]
Thanks for reproduction @alexblunck. It was a regression of https://github.com/nuxt/components/commit/021006680e7d37f0f4aaa1bfe7de8a4692f2eb9e#diff-66a7cd21daf253c27ff7bf07ee5d4e012654afa66f875a08fe00944185b915edR2 for wrongly importing global components. Fixing in short.

**Comment by pi0** [comment]
Fixed in 2.1.5. You can get update by recreating `yarn.lock`/`package-lock.json`

**Comment by alexblunck** [comment]
Great, looks good now. Thank you @pi0 !
