### ISSUE TITLE
Nested components not registered when using prefix in shared library

### ISSUE THREAD

**Issue by dirodriguezm** [nuxt/components#186]
**Describe the bug**
Hello, I followed the instructions for [libary authors](https://github.com/nuxt/components#library-authors) and realized that if I have a `ComponentB` inside a `ComponentA` using a prefix, then in the project using the library, `ComponentB` does not get recognized unless I add the prefix inside `ComponentA`.

**To Reproduce**
`ComponentA.vue`
```vue
<template>
  <ComponentB/>
</template>
```
`ComponentB.vue`
```vue
<template>
  <h1>ComponentB<h1>
</template>
```
`nuxt.js`
```javascript
import { join } from 'path'

export default function() {
  const { nuxt } = this

  // Make sure components is enabled
  if (!nuxt.options.components) {
    throw new Error(
      'please set `components: true` inside `nuxt.config` and ensure using `nuxt >= 2.13.0`'
    )
  }

  this.nuxt.hook('components:dirs', (dirs) => {
    // Add ./components dir to the list
    dirs.push({
      path: join(__dirname, 'components'),
      prefix: 'myprefix'
    })
  })
}
```

Inside the application using the shared component library
`SomeComponent.vue`
```vue
<template>
  <ComponentA>
</template>
```
This shows 
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <ComponentB> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```
**Expected behavior**
The `ComponentB` should be registered in `SomeComponent`

**Additional context**
Defining `ComponentA` as
`ComponentA.vue`
```vue
<template>
  <MyprefixComponentB/>
</template>
```
Works

**Comment by micheldenegri** [comment]
I'm experiencing the same issue. I followed the Migration v1 to v2 documentation and the problem persisted.

**Comment by micheldenegri** [comment]
Actually, I realize I misunderstood the Migration documentation. All you need to do in your component library is to use the `pathPrefix` option and set it to false.

```
import { join } from 'path'

export default function () {
  this.nuxt.hook('components:dirs', (dirs) => {
    dirs.push({
      path: join(__dirname, 'lib'),
      pathPrefix: false
    })
  })
}
```
