### ISSUE TITLE
Not compatible when used with pug

### ISSUE THREAD

**Issue by yutanoma** [nuxt/components#20]
**Describe the bug**

When using the component in a page written in pug syntax, the component seems to be not recognized...

```pug
<template lang="pug">
  div
    ATitle this is a title
</template>
```

<img width="681" alt="スクリーンショット 2020-05-20 15 56 21" src="https://user-images.githubusercontent.com/21168922/82414746-7cfc7f00-9ab2-11ea-8f9f-230d976850a2.png">

However, when I use it with normal HTML syntax, it will work.

```vue
<template>
  <div>
    <ATitle> this is a title </ATitle>
  </div>
</template>
```

<img width="791" alt="スクリーンショット 2020-05-20 15 56 08" src="https://user-images.githubusercontent.com/21168922/82414808-91d91280-9ab2-11ea-93c0-7256e06d7034.png">

I will note that components written with pug syntax in the `/components` directory didn't affect the right functionality.

**To Reproduce**

1. install @nuxt/components (& packages needed to write in pug syntax) by following the right instruction
2. write the page in pug syntax

**Expected behavior**

works with pug syntax

**Screenshots**

**Additional context**

I am using pug with `pug`, `pug-plain-loader`, and `pug-loader`.

**Comment by kevinmarrec** [comment]
@yutanoma **0.3.0** has been released with `pug` support thanks to @florianmientjes , could you confirm it works for you ? :)

**Comment by pi0** [comment]
Hi. Closing as pug supported added with 0.3.0+. Please open a new issue if there is any issue with pug support.
