### ISSUE TITLE
feat: get list of components at runtime

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/components#227]
**Is your feature request related to a problem? Please describe.**
I want to leverage `<component :is="..." />` to load a component dynamically, but I'd also like to know if that component is resolvable (i.e.: it exists) or not.
**Describe the solution you'd like**
I'd like to have a variable injected in the context that tells me the list of components, so that I can throw an error if the component does not exist.

**Comment by kissu** [comment]
Did you tried this one? https://github.com/blokwise/dynamic#readme

**Comment by pi0** [comment]
@kissu Functionality of mentioned package is duplicate in the last version of nuxt/components, you can directly use `<component :is="">` for best performance. And other than for integration with [vue-lazy-hydration](https://github.com/maoberlehner/vue-lazy-hydration) (#104) I do not recommend using it. 

I think what this issue requires, is a way to check the existence of a component before using it. While we can make it sexier with a wrapper component like `<NuxtComponent>` or `$components.has()`, we can do this like this:

```html
<component :is="componentId" v-if="$options.components[componentId]" />
```

Or from js:

```js
import Vue from 'vue'

const componentExists = id => Vue.options.components[id]
```

Sandbox: https://codesandbox.io/s/immutable-wave-umwmz?file=/pages/index.vue:70-100

**Comment by Surt** [comment]
> 

The problem with that is that ```options.components``` only list the "loaded" ones. I can't see how to check if the component can be autoloaded before the ```:is``` to provide a "fallback" component in case the one I'm looking for does not exists (dinamic component name based on options)

**Comment by vhoyer** [comment]
What about this but using vue 3?

**Comment by Rigo-m** [comment]
@vhoyer  in vue3 you can use [resolveComponent](https://vuejs.org/api/render-function.html#resolvecomponent) to check if a component exists. Nuxt/components is not needed in Nuxt3 since components gets auto-imported by the framework itself.
