### ISSUE TITLE
Trouble accessing nuxt modules inside components

### ISSUE THREAD

**Issue by VesterDe** [nuxt/components#26]
**Describe the bug**
My project uses Vuetify, and before I added the component module, this worked: 

```
computed: {
    breakpoint() {
      return this.$vuetify.breakpoint;
    }
  }
```

After adding components, the same file generated an error:

```
Cannot read property 'breakpoint' of undefined
```

I'm also seeing vuex-pathify generate errors of the sort:

 ```
Error in render: "Error: [Vuex Pathify] Unknown module 'library' via path 'library/list'"
```

Are modules generally supposed to be available inside components imported via this module? I'd hope so, otherwise they're useless to me...

nuxt v2.12.2
components v0.3.0

**Comment by Krutie** [comment]
@VesterDe Can you please reproduce the issue on Codesandbox, so that it can be investigated further.

**Comment by VesterDe** [comment]
I tried to get a codesandbox going but didn't manage. I have since solved the issue. I was using typescript files for my store, and when I changed them to .js, it began working again.
