### ISSUE TITLE
How to use Lazy loading component when auto imports for component is disabled?

### ISSUE THREAD

**Issue by xxFREESHROUDxx** [nuxt/components#263]
I wanted to disable auto imports for the components folder for which I did this in the nuxt.config.ts:
`
export default defineNuxtConfig({
components: {
   dirs: []
}
)}
`

which is working perfectly fine. But in for some of the components I want to use the Lazy Loading which I am not able to do as there is no proper documentation on that. Please I need help on this one. Auto imports for composables, util function and other is fine but I just want to disable auto imports for the components folder only.

**Comment by danielroe** [comment]
I'm not sure there's enough information for someone to help.

Are you using Nuxt 3? If so, this is the wrong repository.

Maybe you could provide some code showing what you are trying?

**Comment by xxFREESHROUDxx** [comment]
I wanted to disable auto imports in my components folder but I have now fixed that. Thanks for the help! :)
