### ISSUE TITLE
Render function or template not defined in component folder format

### ISSUE THREAD

**Issue by alvarosaburido** [nuxt/components#29]
**Describe the bug**
Shows error 'render function or template not defined in component' when component is inside of a folder and separated by concern.

```
├── src
│   └── components
│         └── componentC
│           └── componentC.vue
│           └── componentC.js
│           └── componentC.scss
```

**To Reproduce**
Run https://codesandbox.io/s/nuxt-components-p4bze?file=/components/componentC/index.vue

**Expected behavior**
Work Similar to a Single File Component.

NOTE: 

It does work if you name the `.js` file different, for example `componentC.component.js` so it seems like `.vue` and `.js` files cannot be named the same. 

Cloud be that this is just a naming convention thing, so consider if it's valuable enough for you guys to make any change. ✌️ 

Regards

**Comment by pi0** [comment]
Hi @alvarosaburido Indeed it is expected behavior. I added an explicit warning with (#30) about it as well. What you can do is ignoring js extension like this:

```js
export default {
  components: [
    { path: '~/components', pattern: '**/*.vue' }
  ]
}
```

**Comment by alvarosaburido** [comment]
@pi0 awesome,  thanks for the quick response :D

**Comment by pi0** [comment]
Hi again. With 0.3.2, we also added support for `extensions` with docs to make it easier :) 

https://github.com/nuxt/components#extensions
