### ISSUE TITLE
Doesn't work in functional components

### ISSUE THREAD

**Issue by papertokyo** [nuxt/components#31]
**Describe the bug**
When components are referenced in the template of a component with the `functional` attribute on the `template` tag, the client displays "Unknown custom element" and "The client-side rendered virtual DOM tree is not matching server-rendered content" errors. When referenced inside a component with the `functional: true` option, the server displays a "Cannot read property '$createElement' of undefined" error.

**To Reproduce**
Steps to reproduce the behavior: https://codesandbox.io/s/vigorous-wood-9tvfb?file=/pages/index.vue

**Expected behavior**
The referenced component is loaded and rendered as in regular (non-functional) components.

**Screenshots**
![image](https://user-images.githubusercontent.com/8597335/83403330-c630c500-a408-11ea-9ab9-b3e28863fe1c.png)

**Additional context**
This did work in the https://github.com/nuxt-community/global-components package.

**Comment by pi0** [comment]
Actually, functional components are one of the limitations with the components module as we need to extend component options to register discovered components (see [installComponents](https://github.com/nuxt/components/blob/master/lib/installComponents.js#L2)). Will add new option to use global register method similar to global-components (actually plugin is already being generated in `.nuxt/components/components.js`) but also try to investigate if there is any solution for it or not but it is most likely that v1 only supports global option for functional support.

**Comment by pi0** [comment]
Update: #41 ;)

**Comment by papertokyo** [comment]
Providing an array of component names is easy enough. The main thing is not having to use both this and the `global-components` package.

**Comment by pi0** [comment]
Hi @papertokyo [v0.3.4](https://github.com/nuxt/components/blob/master/CHANGELOG.md#034-2020-06-12) is released with functional components support and also (still experimental) `global` option :) 

Thanks for your feedbacks :heart:
