### ISSUE TITLE
Haven't been able to get a version to work since 0.3.0

### ISSUE THREAD

**Issue by toddheslin** [nuxt/components#38]
**Describe the bug**
I installed this on another project @0.3.0 and loved it. Installed 0.3.3 on a new one and it wasn't building my components. Tried 0.3.2, 0.3.1, and eventually settled back on 0.3.0.

This is running on a brand new nuxt install.

**To Reproduce**
1. Install package
2. Add to `buildModules` in `nuxt.config.js`
3. Add component 'Start' in `/components/Start.vue` and reference in `pages/index.vue` as `<Start />`

**Expected behavior**
The component renders.

**Screenshots**
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/1883112/83463732-03f22400-a4c3-11ea-8633-d5056d430355.png">

**Comment by papertokyo** [comment]
That would explain why `0.3.1` wasn't working for me as a module either. I was only able to get it working on `nuxt-edge` (which appears to have it bundled)

**Comment by pi0** [comment]
@toddheslin @papertokyo Apologizes for breaking change. We are still experimenting for stable version to be shipped with nuxt 2.13. You have to add `components: true` to `nuxt.config`

**Comment by papertokyo** [comment]
We've reverted to explicit imports in our project for now. Will the stable version support functional components as well? @pi0 (See https://github.com/nuxt/components/issues/31)

**Comment by pi0** [comment]
@papertokyo Please see https://github.com/nuxt/components/issues/31#issuecomment-637516831 :)

Closing this issue as change is already documented to use `components: true`.

**Comment by toddheslin** [comment]
Thanks @pi0 added a PR for the readme to make it clearer that this option is required regardless of nuxt version.
