### ISSUE TITLE
README.md has a "setup" link but no setup section

### ISSUE THREAD

**Issue by lustremedia** [nuxt/components#40]
**Describe the bug**
The README.md file includes a link to a section called setup but this link does not have an anchor and the section seems to be missing.

**To Reproduce**
Check the README.md for a "setup" section

**Expected behavior**
Either remove the "setup" link or add a "setup" section anchor.

**Comment by pi0** [comment]
Hi. Thanks for making issue readme updated :) Only setup step is setting `components: true` for nuxt 2.13 or current nuxt-edge
