### ISSUE TITLE
Only works up to version 0.2.5

### ISSUE THREAD

**Issue by nathanchase** [nuxt/components#42]
**Describe the bug**
The `@nuxt/components` module works at version 0.2.5. Version 0.3.0 and higher does not.

I'm running nuxt 2.12.2.

I have it included in devDependencies:
```
 "devDependencies": {
    "@nuxt/components": "^0.3.3",
    ...
```

My .vue components are in `/components` - some in the root of `/components`, some in folders under `/components`.

My buildModules are:
```
buildModules: [
    '@nuxtjs/eslint-module', // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/stylelint-module', // Doc: https://github.com/nuxt-community/stylelint-module
    '@nuxt/components', // TODO: Remove when upgrading to nuxt 2.13+
  ],
```
My `build` includes:
```
babel: {
    presets({ isServer }) {
      return [
        [
          require.resolve('@nuxt/babel-preset-app'),
          {
            buildTarget: isServer ? 'server' : 'client',
            corejs: { version: 3 },
          },
        ],
      ];
    },
  },
```
Am I missing something that changed in 0.3.0+?

**Comment by pi0** [comment]
Hi @nathanchase We are still working to release stable 1.0.0 release alongside with nuxt 2.13. You should now add `components: true` in `nuxt.config`: [usage docs](https://github.com/nuxt/components#usage)

```
export default {
  components: true,
  buildModules: [
    '@nuxt/components' // TODO: remove when upgraded to 2.13
 ]
}
```

**Comment by nathanchase** [comment]
Got it. Understood now. The docs led me to believe I was to use only the buildModules declaration until we moved to nuxt 2.13. Adding `components: true` worked with version v0.3.3. Thanks!
