### ISSUE TITLE
Use vuex in Library Authors

### ISSUE THREAD

**Issue by leandromatos-hotmart** [nuxt/components#46]
How to share the state from component library to Nuxt?

I did not find references for work with Nuxt Components and Vuex.

**Comment by pi0** [comment]
Hi. I would suggest not sharing state from component to project as it breaks "props down events up" rule. Components may use `$store` from context but should always check if store is defined and has state. Best would be  making them either atomic or using [dependency injection](https://vuejs.org/v2/guide/components-edge-cases.html#Dependency-Injection)
