### ISSUE TITLE
Question about --production=true not being allowed when using this module.

### ISSUE THREAD

**Issue by pachiraDIG** [nuxt/components#49]
**Describe the bug**
```
FATAL  Module @nuxt/components not found. Please ensure @nuxt/components is in devDependencies and installed. HINT: During build step, for npm/yarn, NODE_ENV=production or --production should NOT be used.
```

**To Reproduce**
Deploy with --production=true in yarn build command.

I don't understand why using this module would mean we can't use `--production` in our builds. Can someone help me understand why this is totally necessary, or at least why it isn't explained in the docs? This is a dealbreaker for me. After making a large amount of changes, I'm now need to uninstall. :(

**Comment by pi0** [comment]
Hi @pachiraDIG can you please try directly using `nuxt-edge` without specifying dependency/devDependency and `buildModules`? Only requirement after 0.3.x is to set `components: true` (or with options)
