### ISSUE TITLE
Template not scanned outside .vue files if imported via src

### ISSUE THREAD

**Issue by alexgrozav** [nuxt/components#53]
**Describe the bug**
If you import template using `<template src="./template.html">`, the file is not scanned for components. 

**To Reproduce**
- Create `index.vue` and `index.html` file
- Instead of writing markup into `<template>`, import the template using `<template src="./index.html">`
- => Components are not available

**Expected behavior**
The html template should be scanned for components and imported.

**Additional context**
I've added the `@nuxt/components` integration to [@inkline/inkline](https://github.com/inkline/inkline) and tested it out. Everything works well except for this. 

You can see it reproduced here: https://codesandbox.io/s/beautiful-sound-skdp6

**Comment by prodoxx** [comment]
I'm having this same issue. Do I just import it manually or what's up?
