### ISSUE TITLE
@nuxt/content with @nuxt/components with global components inconsistency(?)

### ISSUE THREAD

**Issue by yokujin** [nuxt/components#55]
**Describe the bug**
When I use [@nuxt/content](https://github.com/nuxt/content) with global components I receive error:
`render function or template not defined in component: cmp`

**To Reproduce**
1. Clone repository 'https://github.com/yokujin/nuxt-components-content'
2. Run 'yarn install && yarn dev'
3. Open **Listening:** URL and see error

**Expected behavior**
Page content should be: 
```
@@@
Cmp component
@@@
```

**Additional context**
If I change generated `.nuxt/components/plugin.js` into:
```es6
import Vue from 'vue'

+async function () {
  const globalComponents = {
    Cmp: await import('../../components/global/cmp.vue' /* webpackChunkName: "components/global/cmp" */).then(c => c.default || c)
  }

  for (const name in globalComponents) {
    Vue.component(name, globalComponents[name])
  }
}()
```

or use direct `import Cmp from '~/components/global/cmp.vue'` instead of `import().then()` everything works as expected.

**Comment by pi0** [comment]
Hi @yokujin thanks for the report. Should be fixed with [v1.0.1](https://github.com/nuxt/components/releases/tag/v1.0.1). You can use `yarn upgrade nuxt`
