### ISSUE TITLE
`installComponents` is included in client bundle even if components is disabled

### ISSUE THREAD

**Issue by danielroe** [nuxt/components#60]
**Describe the bug**
`installComponents` is included in client bundle even if `components: false` is included in `nuxt.config`.

**To Reproduce**
1. Clone repository https://github.com/danielroe/nuxt-components-ts
2. Run `yarn build`
3. Inspect `.nuxt/dist/client/app.js`

**Expected behavior**
I expect this not to be included in the client bundle.

**Additional context**
I encountered this in a production application when diagnosing an issue with IE11 where this function ended up using an arrow function, but I have yet to reproduce.

**Comment by pi0** [comment]
Hi @danielroe. IE support should be fixed by (https://github.com/nuxt/components/commit/201914bd71b4b4c7215e0da1d705984991a38b53) (you can use `yarn upgrade nuxt` to install 1.0.3+). But this issue is valid and confirming (https://github.com/nuxt/components/issues/56#issuecomment-647604391).

**Comment by pi0** [comment]
fixed by #60
