### ISSUE TITLE
Not working when component is in directory.

### ISSUE THREAD

**Issue by saerose** [nuxt/components#66]
**Describe the bug**
I tried everything I found on the docs but when I try to use a component that has it's own directory inside the components folder it does not work. I get an error message:

`[Vue warn]: Unknown custom element: <NavigationELHeader> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

This does not happen on the components I have on the root component folder.

I added the element on nuxt.config.js like this:
```
  components: [
    '~/components',
    { path: '~/components/Navigation/', prefix: 'Navigation' },
  ],
```

And also added it to buildModules.
Then I tried to use the component as `<NavigationComponentNameInsideTheDirectory />` but it's when I get the error. 

I'm doing something wrong?

**Comment by bauer01** [comment]
@saerose I had same problem but https://github.com/nuxt/components/issues/62#issuecomment-650724468 solved it ;-)

**Comment by saerose** [comment]
Sorry but not related to scoped styles, all the site has scoped styles and the components that are on the main component directory are loaded. The problem comes when I have sub-directories. And yeah, I had that option set at first at `nuxt.config.js `but was not working.

**Comment by saerose** [comment]
@bauer01 And how you solved it? I read the issue but I'm not sure I understand.

**Comment by pi0** [comment]
Hi. Would you please fork [components sandbox](https://codesandbox.io/s/github/nuxt/components/tree/master/example) to reproduce issue?

**Comment by saerose** [comment]
Hi! It was just a component (the one I used as an example) that was giving me the issue and it magically fix (I did nothing so I really don't understand what happened). I finally decided to use the renaming all components inside a sub-directory with the directory prefix option. Closing!
