### ISSUE TITLE
Webpack Preload comments for LazyLoad (And comments in general)

### ISSUE THREAD

**Issue by Sshuichi** [nuxt/components#71]
**Is your feature request related to a problem? Please describe.**
When I lazyload a component, I still want it to be preloaded. This is why I use Webpack comments: 
```
const Header = () => import(/* webpackPreload: true */ '@/components/Header')
```
With LazyComponent, I don't know how to do it. 

**Describe the solution you'd like**
Something like 
`<LazyHeader /* webpackPreload: true */ />`

**Describe alternatives you've considered**
Use the usual dynamic imports

**Comment by dpashovski** [comment]
I'm looking for something like this as well...
