### ISSUE TITLE
CHG recomm'd on the way to require Webpack exports

### ISSUE THREAD

**Issue by mcdmaster** [nuxt/components#77]
**Is your feature request related to a problem? Please describe.**
- Building web apps using Webpack + Components modules always faces error.

**Describe the solution you'd like**
- The error message tells me that the filepath of RuleSet.js has been changed since upgrade of Webpack from 4x to 5.x (currently Beta).

**Describe alternatives you've considered**
- Since Webpack itself provides with exports including RuleSet, the the endpoint on the Webpack should be treated as SPoC.

**Additional context**
- Will update shortly. Thanks

**Comment by pi0** [comment]
Hi @mcdmaster thanks for PR. Actually, nuxt@2 is depending on webpack@4 and webpack@5 is used for nuxt@3 only.
