### ISSUE TITLE
Prefix and beginning of component name can't be the same

### ISSUE THREAD

**Issue by simpsonphile** [nuxt/components#79]
**Describe the bug**
If components prefix is same as beginning of component name for example: l-loader, l-label-default then it is not importing and I'm facing an error: 

"Unknown custom element: <l-label-default> - did you register the component correctly? For recursive components, make sure to provide the "name" option."

**Comment by hoquangthaiholy** [comment]
I face the same problem :(

**Comment by pi0** [comment]
Hi. Would you please share directory structure and components config (if used)?

**Comment by hoquangthaiholy** [comment]
My directory looks like this:

```
components/
   case-ccc.vue
   case-ccc-1-2-3e.vue
   case-ccc-1-3-4c.vue
   ...
```

component `case-ccc` is working well but others are not.

**Comment by cballevre** [comment]
Hi, it's also the same for me. Just to add some context.

My directory looks like this:

```
components/
  t/
    InputWithValidation.vue
    TextareaWithValidation.vue
    ...
```

And my config looks like this: 

```
{
  path: '~/components/t',
  prefix: 'T'
},
```

If I trie to import `<t-textarea-with-validation />` then the component can load. It's work fine if I change the prefix to `TU` or something that doesn't match the first letter of the component.

**Comment by ivodolenc** [comment]
I also face a similar problem with `auto import` when the component name contains a number.

Here is a [codesandbox](https://codesandbox.io/s/nuxt-components-auto-import-bug-8xkjq)

**Comment by StEvUgnIn** [comment]
I face this problem for my components with the setting 
```
export default {
  component: true
}
```

My configuration:
nuxt : latest (v2.14.12)
express : v4.17.1
spdy : v4.0.2

**Comment by StEvUgnIn** [comment]
I found a workaround. 
Link here : #92

**Comment by manniL** [comment]
> 
> 
> I also face a similar problem with `auto import` when the component name contains a number.
> 
> Here is a [codesandbox](https://codesandbox.io/s/nuxt-components-auto-import-bug-8xkjq)

This is due to the naming scheme.
`<app-h-1>HEADING 1</app-h-1>` or `<AppH2>HEADING 2</AppH2>` does work.

**Comment by ivodolenc** [comment]
> This is due to the naming scheme.

@manniL I realized it might have something to do with the naming, but when imported manually, it works. Anyway, thanks for your time

**Comment by pi0** [comment]
With nuxt 2.15 (components v2), double prefix should be resolved and also full path prefix is being used. If you would like to disable and use filename as final component name, can disable `pathPrefix` option:

```js
components: [
  { path: '~/components', pathPrefix: false }
]
```

Also, there is a CLI output linking to `components/readme.md` that can help to find-out generated component names.

BTW if you felt something is wrong with auto-generated component names in nuxt@2.15+, feel free opening an issue.
