### ISSUE TITLE
Add support for auto importing directives

### ISSUE THREAD

**Issue by pimlie** [nuxt/components#8]
**Is your feature request related to a problem? Please describe.**

I am too lazy to import directives manually

**Describe the solution you'd like**

Just parse my template for any `v-` attributes, search for matching js files and add them to the component. This is one I sometimes use: https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/src/directives/visible but there is also https://github.com/Akryum/vue-observe-visibility

**Describe alternatives you've considered**

I considered doing it manually but I am too lazy

**Additional context**

Components and directives share the same premise with regards to the need for importing them, so it makes sense to support them too.

**Comment by pi0** [comment]
Since loader is now optional, this feature is more likely to be not easily possible. Using global directives via a plugin for this situation would be probably best.
