### ISSUE TITLE
Lazy loaded Component shouldn't be prefixed with Lazy

### ISSUE THREAD

**Issue by dmx374** [nuxt/components#83]
Dynamically (lazy loaded) components shouldn't be prefixed with Lazy. It adds confusion and can become dirty pretty quickly (especially I have a bunch of custom components in an other project with names already beginning with Lazy, like LazyLoad, LazySpin etc.)

So, instead of this:
```
<template>
  <LazyComponentFoo v-if="foo" />
  <button @click="foo=true">Load Foo</button>
</template>
```
you should use an explicit attribute (like defer, or lazy, IDN), maybe like this:
```
<template>
  <ComponentFoo defer v-if="foo" />
  <button @click="foo=true">Load Foo</button>
</template>
```

**Comment by judehunter** [comment]
yeah, I also felt it was a weird design choice.
adding an attribute/directive would be much better

**Comment by papertokyo** [comment]
Agree. An attribute/directive would fit in better not just with Vue's API but html itself. Like how you have attributes like `async`, `defer`, and `preload` on script and link tags.

**Comment by drewbaker** [comment]
Agree!

**Comment by pi0** [comment]
Supporting attribute requires having a loader that is not always working (global components and development mode). Still, you have a better prefix suggestion, which is more than welcome. We can easily add as an alias to [plugin](https://github.com/nuxt/components/blob/6ba6d2243a0ebac2acc515ded3003827f62f7505/templates/components/plugin.js#L15)

**Comment by drewbaker** [comment]
Ok, if no directive, is it weird to do something like:

MyComponentName.lazy.vue

But the directive approach was better for sure as it allowed you to opt into lazy loading for that use of the component, rather than always lazy loading it always.

**Comment by pi0** [comment]
Nice idea @drewbaker! I've created #180 to check different options we could have for naming
