### ISSUE TITLE
Add export method to know which/where a component is imported

### ISSUE THREAD

**Issue by pimlie** [nuxt/components#9]
**Is your feature request related to a problem? Please describe.**

Although automation is really cool, sometimes (eg when debugging) you need to be able to exactly know what exactly happens where.

**Describe the solution you'd like**

A way to export the component imports that are automatically added. I can think of three possibilities:
- Inject the import statements directly into the SFC
```js
// my-component.vue
export default {
  components: {
    /* start @nuxt/component imports */
    put the auto added imports between comments
    /* end @nuxt/component imports */
```
- Export the import statements per SFC which can then also be used to manually import them. Eg given `my-component.vue` the imports are exported to `my-component.imports.js`. Then in your SFC you could do:
```js
// my-component.vue
import components from './my-component.imports.js'
export default {
  components
}
```
- Export/print one big dependency tree that starts with pages and then traverses down the imported component tree and prints the auto added imports

**Describe alternatives you've considered**
n.a.

**Additional context**

Consider the situation where a component could be resolved from different folders you configured. Im guessing that atm we will just use the first match that is found, but if you dont remember anymore you had two similar named components in different folders it can get confusing quickly. This feature request should help with that.

If we would go for option 1 or 2 then we would also solve the Jest issue (or any other tool that implements their own require) in a good way.

In general I think the auto import is very cool, but fully obfuscating which imports are used where can get very confusing in bigger apps

**Comment by pi0** [comment]
Indeed automation can be sometimes so confusing. While thinking of better solution to be able to browse discovered components, in latest version an `md` file is auto generated to list names and paths:

![image](https://user-images.githubusercontent.com/5158436/113773428-4d844e80-9726-11eb-8f1a-f8347d96a23a.png)
