### ISSUE TITLE
Module incompatible with recursive components

### ISSUE THREAD

**Issue by algoth** [nuxt/components#92]
**Describe the bug**

I was using the nuxt global components module before this module came out. I have a few components which I am using recursively. Code below. That was working as I was naming the components as required by Vue to use them recursively. 

However, after upgrading to 2.14.3 and nuxt components modules, I am getting the below error for recursive components: 

Unknown custom element: <CaseObject> - did you register the component correctly? For recursive components, make sure to provide the "name" option

My components are still named. See the example below

```
<template>
   <div >
        <div
                v-for="(item2,propertyName2) in item"
                :key="propertyName2"
            >
               
            <p class="font-weight-bold title mt-5 primary--text" v-if="typeof item2 === 'object' && !property && !(item2 instanceof Date)">{{ propertyName2.replace(/_/g, ' ') | capitalize }}</p>

            <p class="font-weight-bold text--secondary" v-else-if="typeof item2 === 'object' && !(item2 instanceof Date)">{{ propertyName2.replace(/_/g, ' ') | capitalize }}</p>

            <CaseItem v-if="(typeof item2 !== 'object' && !Array.isArray(item2)) || (item2 instanceof Date)" :item='item2' :property="property ? `${property}.${propertyName2}` : propertyName2" />
            
            <CaseObject v-if="typeof item2 === 'object' && !Array.isArray(item2) && !(item2 instanceof Date)" :item="item2" :property="property ? `${property}.${propertyName2}` : propertyName2"/>
            
            <CaseArray v-if="Array.isArray(item2)" :item="item2" :property="property ? `${property}.${propertyName2}` : propertyName2"
                        />
                
        </div>
        
   </div>
</template>

<script>


export default {
    name: 'CaseObject',


```

**Expected behavior**
Components should work recursively

**Screenshots**

<img width="930" alt="Screenshot 2020-08-23 at 12 08 53 AM" src="https://user-images.githubusercontent.com/3228365/90963406-f7cf9e80-e4d4-11ea-9aad-ec53cdf66374.png">

**Additional context**
Recursive components still working fine with the nuxt global components module

**Comment by algoth** [comment]
@pi0 is there a workaround / fix for this. Stuck with this issue. Pls advice

**Comment by vampics** [comment]
+ 1

**Comment by bztest1** [comment]
same story if I use `<component :is="myDynamicComponentName" />`

**Comment by simpsonphile** [comment]
+1

**Comment by davidturtle** [comment]
+1

**Comment by kevinmarrec** [comment]
Can people confirm that it works during SSR and then failed on client ?

I've been able to see good output, then when client is hydrated there come the error (hydration mismatching nodes error + unknown custom element)

**Comment by LeCoupa** [comment]
@kevinmarrec Yes, it works during SSR but fails on client.

**Comment by LeCoupa** [comment]
While this problem persists, a fix is to keep importing the not-found components inside the file.

**Comment by LeCoupa** [comment]
I really love this package. Unfortunately, when you have a project with nested components, you have to revert back to basic imports. Just wondering if there is an ETA for fixing this issue?

**Comment by fabianwohlfart** [comment]
+ 1

I get my recursive components working with putting the Item, in your case »CaseItem« to lazy: »LazyCaseItem«.
It (the html from it) also gets generated with `npm run generate`. Is this a safe option?

**Comment by StEvUgnIn** [comment]
Did anyone find any solution or should I downgrade my version of nuxt?

**Comment by LeCoupa** [comment]
@StEvUgnIn I think you should downgrade. This issue is not fixed yet.

**Comment by StEvUgnIn** [comment]
I am surprised that I meet this issue when I run my custom server based on `express` and `spdy`, but not with `nuxt` internal server...

**Comment by StEvUgnIn** [comment]
I fixed the bug in my project. It was due to babel transpilation. If you are using babel, make sure to disable it on Vue components.

**Comment by lukasborawski** [comment]
@StEvUgnIn how you’re doing this? Using ignore in babel config, or anyhow? Thanks.
