### ISSUE TITLE
Override component name with attribute name declare in vue file

### ISSUE THREAD

**Issue by nguyenduclong-ict** [nuxt/components#95]
## Please acept overide component name with attribute name declare in vue file

I want override component name with name in vue file.
Ex:
```javascript
export default {
   name : 'TestComponent',
}
```

**Comment by Atinux** [comment]
Hi @nguyenduclong-ict 

Actually this is not possible since we cannot parse the Vue files inside, also, I don't consider it a best practice to have a different name than the filename.
